# Generated by Django 5.2.16 on 2026-09-08 12:33

import django.db.models.deletion
import django.db.models.functions.text
import inventory.images
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.CharField(blank=True, help_text='Box, crate, or bag this item is stored in.', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_is_approximate',
            field=models.BooleanField(default=False, help_text='Check if the count is estimated (e.g. screws, cable ties).'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.images.item_photo_upload_to),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='project_name_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.project'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['container'], name='inventory_i_contain_b20545_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['project'], name='inventory_i_project_5e7620_idx'),
        ),
    ]
