# Generated by Django 5.2.16 on 2026-09-08 13:16

from django.db import migrations


def copy_types_to_categories(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    Category = apps.get_model("inventory", "Category")
    for item in Item.objects.exclude(item_type=None).select_related("item_type"):
        name = item.item_type.name
        cat = Category.objects.filter(name__iexact=name).first()
        if cat is None:
            cat = Category.objects.create(name=name)
        item.categories.add(cat)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_item_project_container_approx_qty"),
    ]

    operations = [
        migrations.RunPython(copy_types_to_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="item",
            name="item_type",
        ),
        migrations.DeleteModel(
            name="ItemType",
        ),
    ]
