# Generated by Django 5.2.16 on 2026-09-09 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_type_into_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes_current', to='inventory.location')),
                ('scope_location', models.ForeignKey(blank=True, help_text='If set, only items in this room (and its places) are expected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes_scoped', to='inventory.location')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_expected', to='inventory.location')),
                ('found_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_found', to='inventory.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_scans', to='inventory.item')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_scans', to=settings.AUTH_USER_MODEL)),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='inventory.stocktake')),
            ],
            options={
                'indexes': [models.Index(fields=['stocktake', 'scanned_at'], name='inventory_s_stockta_695933_idx')],
                'constraints': [models.UniqueConstraint(fields=('stocktake', 'item'), name='one_scan_per_item_per_stocktake')],
            },
        ),
    ]
