# Generated by Django 5.2.16 on 2026-09-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_stocktake"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="installed_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Another inventory item this one is built into.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installed_parts",
                to="inventory.item",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["installed_in"], name="inventory_i_install_64662b_idx"),
        ),
    ]
