# Generated by Django 5.2.16 on 2026-09-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_installed_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='installed_in',
            field=models.ForeignKey(blank=True, help_text='Another inventory item this one is mounted on.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_parts', to='inventory.item', verbose_name='mounted on'),
        ),
    ]
