# Generated by Django 5.2.16 on 2026-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_mounted_on_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakescan',
            name='counted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktakescan',
            name='expected_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
