# Generated by Django 5.2.16 on 2026-09-30 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktake_scan_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_group',
            field=models.UUIDField(blank=True, editable=False, help_text='Items sharing this value are units of the same type.', null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['unit_group'], name='inventory_i_unit_gr_32685c_idx'),
        ),
    ]
